USE JSadvClassSpring2015;
CREATE TABLE IF NOT EXISTS stuff (
	id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,        
        fname VARCHAR(50) NOT NULL,
        colors VARCHAR(50) NOT NULL,
        ranges VARCHAR(50) NOT NULL,
        dob VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;

